name: Bug Report
description: Is the package not working as intended?
title: BUG - (brief description)
labels:
  - 🐞 Bug
assignees: LuisFerLCC

body:
  - type: markdown
    attributes:
      value: |
        <div align="center" style="margin-bottom: 0.5rem">
        <img src="https://raw.githubusercontent.com/float-toolkit/react/HEAD/media/ftreact.svg" width="100" />
        </div>

        <h1 align="center">Bug Report</h1>

        **IMPORTANT:** IF YOU WANT TO REPORT A SECURITY VULNERABILITY, PLEASE USE [SECURITY ADVISORIES](https://github.com/float-toolkit/react/security/advisories/new) TO FILE A PRIVATE REPORT.

  - type: dropdown
    id: affects-core-package
    attributes:
      label: Affects core package
      description: Does this bug affect `@float-toolkit/core` as well?
      options:
        - "Yes"
        - "No"

  - type: input
    id: package-version
    attributes:
      label: Package version
      description:
        Which package version are you using? You can check it in your `package.json` file or by running `npm list <package>`.
      placeholder: X.X.X
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please describe the bug and how to reproduce it in as much detail as possible.
        You can also attach images or log files here.
      placeholder: |
        Steps to reproduce:
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: |
        If possible, include a reproducible code sample. The sample should be minimal (with no unnecessary code) but complete.
        NOTE: This input will be automatically formatted into JavaScript/TypeScript code.
      render: TypeScript
      placeholder: |
        import useFloatToolkit from "@float-toolkit/react";

        // in function component
        const { add, output } = useFloatToolkit();

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug? (please be realistic)
      options:
        - Minor bug (annoying, but not crucially broken)
        - Medium bug (needs attention)
        - Major bug (must be fixed immediately)
    validations:
      required: true

  - type: checkboxes
    id: contribution-guidelines
    attributes:
      label: Contribution guidelines
      description: By submitting this issue, you agree that...
      options:
        - label: This is a bug, not you [asking for support](https://github.com/float-toolkit/react/discussions/categories/q-a).
          required: true
        - label:
            You have read the [documentation](https://float-toolkit.web.app) and [README
            file](https://github.com/float-toolkit/react/blob/master/README.md), and made sure this is not intended behavior.
          required: true
        - label: The issue has not already been reported.
          required: true
        - label:
            You are following the project's [Code of
            Conduct](https://github.com/float-toolkit/react/blob/master/.github/CODE_OF_CONDUCT.md) and [contribution
            guidelines](https://github.com/float-toolkit/react/blob/master/.github/CONTRIBUTING.md).
          required: true
