import PackageJSON from "../package.json" assert { type: "json" };
import { writeFileSync } from "fs";

const numbers = PackageJSON.version.split(".");
writeFileSync(
	"src/__autogenerated__/versionNumbers.ts",
	`/**
 * @internal
 */
export const versionNumbers = ${JSON.stringify(numbers)};`
);
