name: Test with Vitest

on:
  push:
    branches-ignore:
      - stable

  workflow_dispatch:

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
